[features]
seeds = false
skip-lint = false
[programs.localnet]
favorites = "G6z9NGz4WB2acHbGQdycnHtPyBSF5vSB3qeejNE6Fno9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
